const DOMSelectors = {
  button: document.querySelector(".button"),
  body: document.querySelector("body"),
};

const albums = [
  {
    name: "Future Nostalgia",
    genre: "Pop",
    language: "English",
    image: "./Images/cover1.jfif",
    price: 9.99,
  },
  {
    name: "folklore",
    genre: "Indie Folk",
    language: "English",
    image: "./Images/cover2.jfif",
    price: 12.99,
  },
  {
    name: "Blonde",
    genre: "R&B",
    language: "English",
    image: "./Images/cover3.jfif",
    price: 14.99,
  },
  {
    name: "The Dark Side of the Moon",
    genre: "Progressive Rock",
    language: "English",
    image: "./Images/cover4.jfif",
    price: 15.99,
  },
  {
    name: "Abbey Road",
    genre: "Rock",
    language: "English",
    image: "./Images/cover5.jpg",
    price: 11.99,
  },
  {
    name: "DAMN.",
    genre: "Hip-Hop",
    language: "English",
    image: "./Images/cover6.jfif",
    price: 13.99,
  },
  {
    name: "Divide",
    genre: "Pop",
    language: "English",
    image: "./Images/cover7.jfif",
    price: 9.99,
  },
  {
    name: "After Hours",
    genre: "R&B",
    language: "English",
    image: "./Images/cover8.jfif",
    price: 12.99,
  },
  {
    name: "Lover",
    genre: "Pop",
    language: "English",
    image: "./Images/cover9.jfif",
    price: 10.99,
  },
  {
    name: "In the Lonely Hour",
    genre: "Pop Soul",
    language: "English",
    image: "./Images/cover10.jfif",
    price: 11.49,
  },
  {
    name: "A Night at the Opera",
    genre: "Rock",
    language: "English",
    image: "./Images/cover11.jfif",
    price: 13.99,
  },
  {
    name: "Back to Black",
    genre: "Soul",
    language: "English",
    image: "./Images/cover12.jfif",
    price: 9.99,
  },
  {
    name: "No. 6 Collaborations Project",
    genre: "Pop/Rap",
    language: "English",
    image: "./Images/cover13.jfif",
    price: 11.99,
  },
  {
    name: "The Fame",
    genre: "Pop",
    language: "English",
    image: "./Images/cover14.jfif",
    price: 8.99,
  },
  {
    name: "Unorthodox Jukebox",
    genre: "Pop/Funk",
    language: "English",
    image: "./Images/cover15.jfif",
    price: 9.99,
  },
  {
    name: "The College Dropout",
    genre: "Hip-Hop",
    language: "English",
    image: "./Images/cover16.jfif",
    price: 12.49,
  },
  {
    name: "The Rise and Fall of Ziggy Stardust and the Spiders from Mars",
    genre: "Glam Rock",
    language: "English",
    image: "./Images/cover17.jfif",
    price: 10.99,
  },
  {
    name: "Viva La Vida or Death and All His Friends",
    genre: "Alternative Rock",
    language: "English",
    image: "./Images/cover18.jfif",
    price: 11.99,
  },
  {
    name: "In the Aeroplane Over the Sea",
    genre: "Indie Rock",
    language: "English",
    image: "./Images/cover19.jfif",
    price: 15.49,
  },
  {
    name: "good kid, m.A.A.d city",
    genre: "Hip-Hop",
    language: "English",
    image: "./Images/cover20.jfif",
    price: 13.49,
  },
];

export { DOMSelectors };
export { albums };
